apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
description: "Deny all egress traffic except DNS"
metadata:
  name: "ccnp-test"
spec:
  endpointSelector: {}
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            "k8s:io.kubernetes.pod.namespace": kube-system
      toPorts:
      - ports:
         - port: "53"
           protocol: ANY
        rules:
          dns:
            - matchPattern: "*"
